name: Publish NuGet Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      packages: write
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: "patch" 

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build and Pack
      run: dotnet pack --configuration Release -p:PackageVersion=${{ steps.tag_version.outputs.new_version }}

    - name: Push to GitHub Packages
      run: dotnet nuget push "InnoShop.Contracts/bin/Release/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/d1amond09/index.json"
